Vagrant.configure("2") do |config|
	(1..3).each do |i|
		config.vm.define "master#{i}" do |master|
			master.vm.box = "hashicorp/bionic64"
			master.vm.hostname = "master#{i}"
			master.vm.network "public_network", bridge: "Realtek PCIe GBE Family Controller", ip: "192.168.15.11#{i}"
			master.vm.provision "shell", path: "docker-kube.sh"
			master.vm.provider :virtualbox do |m|
				m.customize ["modifyvm", :id, "--name", "master#{i}"]
				m.customize ["modifyvm", :id, "--memory", 512]
				m.customize ["modifyvm", :id, "--cpus", 1]
				m.customize ["modifyvm", :id, "--vram", 16]
				m.customize ["modifyvm", :id, "--vrde", "off"]
			end
		end
	end
	(1..3).each do |i|
		config.vm.define "worker#{i}" do |worker|
			worker.vm.box = "hashicorp/bionic64"
			worker.vm.hostname = "worker#{i}"
			worker.vm.network "public_network", bridge: "Realtek PCIe GBE Family Controller", ip: "192.168.15.11#{i+2}"
			worker.vm.provision "shell", path: "docker-kube.sh"
			worker.vm.provider :virtualbox do |w|
				w.customize ["modifyvm", :id, "--name", "worker#{i}"]
				w.customize ["modifyvm", :id, "--memory", 512]
				w.customize ["modifyvm", :id, "--cpus", 1]
				w.customize ["modifyvm", :id, "--vram", 16]
				w.customize ["modifyvm", :id, "--vrde", "off"]
			end
		end
	end		
end